### ISSUE TITLE
Looking for freelancers

### ISSUE THREAD

**Issue by andreasnuesslein** [tunga-io/tunga-api#108]
Hey all,

my name is Andreas and I’m the teach lead for an NGO called Future Challenges in Germany. Our organization is focused on human rights issues and currently we are in the middle of a project about human rights in Uganda. The project is funded by the GIZ (Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ) GmbH or German Corporation for International Cooperation GmbH) which gets most of their assignments from the German state.

In a first step we need somebody (or rather a team) to build a small website for this project and we would like that website to be built with wagtail.io with a volume of roughly 5 days work.
UX design would be also helpful and compensated extra (~2-3 days).

The main goal of the whole project is however developing or enhancing a communication platform with a much bigger budget. The specifics however on this are not completely clear yet. Therefore we want to start with step one and see how it goes from there.

We specifically ask Ugandan developers because one goal of the project is to have as much project money as possible go directly to the Ugandan people.

Cheers
Andreas

PS: Sorry for contacting you this way; github doesn't really allow direct messages.

**Comment by bartleijssenaar** [comment]
Hi Andreas, 

Good to hear from you. Any channel to reach us is fine ;-). 
It would be great to learn more about this website and the project. 

Shall we schedule a call to discuss the details?
You can best reach me on bart@tunga.io.

**Comment by bartleijssenaar** [comment]
Hello @andreasnuesslein! Hope to hear from you soon.

**Comment by andreasnuesslein** [comment]
Hey @bartleijssenaar  sorry for not getting back earlier; I came down with the flu.

If you don't mind me asking: I'm assuming you are from the dutch office - would it be possible to make sure the budget for this project goes 100% to the Ugandans? It's quite paramount for this project.

Here you can find general information about the project:
https://futurechallenges.org/local/news/digital-human-rights-work-in-uganda/

And concerning the first leg of the coding:
Basically we need a little "Wordpress-esk" page, nothing too fancy, but we would like it in Wagtail. Just the usual. Blog pages / "Articles", Static pages, ability to add video and image to the content (so just regular RichtextField, probably no StreamFields in the beginning).

As I said, If the first step is satisfying for everybody, there's the option for a much bigger task that is not exactly clear yet. One idea is to take matrix (matrix.org) and maybe riot and integrate it into an existing collaboration platform (maybe wechange.de).

Anyways - let me know if the budget thing is possible and if you had somebody at Tunga in Uganda to oversee this :)

Cheers

**Comment by bartleijssenaar** [comment]
@andreasnuesslein, 

It is no problem to work exclusively with developers from Uganda. 

Do you already have (part of the) the content or designs? Based on the current information I can't give you an accurate estimate.

Can you share you details per email (bart@tunga.io)? This will make communication easier.

**Comment by andreasnuesslein** [comment]
Yes let me get in contact with you that way :)

**Comment by andreasnuesslein** [comment]
Hey @bartleijssenaar 

sorry but I have to go back to this question once more because it's paramount for our financiers:

I asked if all the budget we would put into this website would go to Ugandan people and you said:
> It is no problem to work exclusively with developers from Uganda.

Does that mean to if we pay x €, that x € will go to Ugandan people/developers or will the Tunga B.V. get a cut and x-y € will go to Uganda?

I need to be insistent because our financiers are insistent there too.

Cheers

**Comment by bartleijssenaar** [comment]
Hi @andreasnuesslein, no problem.
A part (y) will go to our Dutch entity.

**Comment by andreasnuesslein** [comment]
Ahoy @bartleijssenaar so sadly that's a deal breaker for our financiers :S . Thank you for your willingsness though and maybe another time.

Cheers

**Comment by bartleijssenaar** [comment]
That's a shame. Best of luck and you know where to find us now.

Kind regards!
