### ISSUE TITLE
(EUR 30) Update HubSpot contact information saved when a client completes wizard on Tunga.io

### ISSUE THREAD

**Issue by davidsemakula** [tunga-io/tunga-api#23]
## I'm submitting a ...

<pre><code>
[ ] Bug report 
[x] Feature request
[ ] Regression (behavior that used to work and stopped working in a new release)
</code></pre>

## Current behavior

When a new user is created and synced with HubSpot, only their contact information is added

## Expected behavior

For user's of type project owner we'd like to set the following as well
- lifecycle stage should be set to ‘Opportunity’
- owner should be set to Domieck
- a (custom) tag should be added to this client ID named ‘wizard call’ if the user source was wizard (https://github.com/tunga-io/tunga-api/blob/develop/tunga_auth/models.py#L32)

https://github.com/tunga-io/tunga-api/blob/develop/tunga_auth/signals.py#L32
https://github.com/tunga-io/tunga-api/blob/develop/tunga_auth/tasks.py#L12-L29

## Please tell us about your environment (optional for feature requests)

<pre><code>

Environment/ Server:
- [ ] Production
- [ ] Staging
- [ ] Test
- [ ] Development

Developer environment:
- Python version: XX 
- Django version: XX 
- Platform: 

Others:

</code></pre>

**Comment by Ihure** [comment]
@davidsemakula hi from what I understand the task at hand is for user's of type project owner I set

- [ ] lifecycle stage to ‘Opportunity’

- [ ] set owner to Domieck

- [ ] add a tag to client ID named 'wizard call' if source is wizard

**Comment by davidsemakula** [comment]
@Ihure yes ... I also pointed u to the interesting points in the code, the model, the signal and the task that actually performs the huspot contact creation
